# Generated by Django 5.2.1 on 2025-08-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeApi', '0034_alter_place_place_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Front',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='front/logo_images/')),
                ('heading', models.CharField(max_length=255)),
                ('subheading', models.CharField(max_length=255)),
                ('paragraph', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
