# Generated by Django 5.2.1 on 2025-08-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeApi', '0035_front'),
    ]

    operations = [
        migrations.AddField(
            model_name='front',
            name='company_logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='front/company_logo/'),
        ),
    ]
