# Generated by Django 5.2.1 on 2025-09-05 14:02

import placeApi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeApi', '0037_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user_name',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='front',
            name='company_logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='front/company_logo/', validators=[placeApi.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='front',
            name='heading',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='front',
            name='logo_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='front/logo_images/', validators=[placeApi.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='front',
            name='subheading',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='gallery/photos/', validators=[placeApi.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='items/images/', validators=[placeApi.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='itineraryphoto',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='places/itinerary_photos/', validators=[placeApi.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='place',
            name='exclude',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='place',
            name='include',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='place',
            name='main_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='places/main_images/', validators=[placeApi.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='place',
            name='package_title',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='place',
            name='price_title',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='place',
            name='subtitle',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='place',
            name='tour_highlights',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='places/sub_images/', validators=[placeApi.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='post_images/', validators=[placeApi.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_url',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='services/', validators=[placeApi.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_title',
            field=models.CharField(blank=True, default=''),
        ),
    ]
